# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(994, 737)
        MainWindow.setMinimumSize(QtCore.QSize(994, 737))
        MainWindow.setMaximumSize(QtCore.QSize(994, 737))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/pokeball.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(235, 0, 0);")
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(30, 90, 501, 431))
        self.frame.setStyleSheet("background-color: #9de1f6;\n"
"border-radius:15px;\n"
"border: 3px solid black;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.lbl_pokeimg = QtWidgets.QLabel(self.frame)
        self.lbl_pokeimg.setGeometry(QtCore.QRect(10, 10, 481, 401))
        self.lbl_pokeimg.setStyleSheet("border:none")
        self.lbl_pokeimg.setText("")
        self.lbl_pokeimg.setPixmap(QtGui.QPixmap("../img/002.png"))
        self.lbl_pokeimg.setObjectName("lbl_pokeimg")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(30, 19, 501, 61))
        self.frame_2.setStyleSheet("Border-radius:15px;\n"
"background-color: #9de1f6;\n"
"border: 3px solid black;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(10, 14, 481, 33))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(20)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label.setStyleSheet("Border:none;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(30, 540, 501, 81))
        self.frame_4.setStyleSheet("Border-radius:15px;\n"
"background-color: #9de1f6;\n"
"border: 3px solid black;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.lbl_id = QtWidgets.QLabel(self.frame_4)
        self.lbl_id.setGeometry(QtCore.QRect(10, 20, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(28)
        font.setBold(True)
        self.lbl_id.setFont(font)
        self.lbl_id.setStyleSheet("border:none;")
        self.lbl_id.setObjectName("lbl_id")
        self.txtedt_desc = QtWidgets.QTextEdit(self.frame_4)
        self.txtedt_desc.setGeometry(QtCore.QRect(130, 20, 361, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(10)
        font.setBold(True)
        self.txtedt_desc.setFont(font)
        self.txtedt_desc.setStyleSheet("border:none;")
        self.txtedt_desc.setReadOnly(True)
        self.txtedt_desc.setObjectName("txtedt_desc")
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        self.frame_5.setGeometry(QtCore.QRect(30, 630, 501, 41))
        self.frame_5.setStyleSheet("Border-radius:15px;\n"
"background-color: #9de1f6;\n"
"border: 3px solid black;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit.setGeometry(QtCore.QRect(10, 10, 361, 21))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(11)
        font.setBold(True)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("border:none;")
        self.lineEdit.setObjectName("lineEdit")
        self.btn_search = QtWidgets.QPushButton(self.frame_5)
        self.btn_search.setGeometry(QtCore.QRect(412, 2, 91, 36))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(11)
        font.setBold(True)
        self.btn_search.setFont(font)
        self.btn_search.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);}\n"
"\n"
"QPushButton:Hover{\n"
"background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 0, 0);\n"
"\n"
"}\n"
"\n"
"QPushButto:Pressed{\n"
"background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);}\n"
"")
        self.btn_search.setObjectName("btn_search")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(550, 20, 421, 631))
        font = QtGui.QFont()
        font.setUnderline(False)
        self.frame_3.setFont(font)
        self.frame_3.setStyleSheet("Border-radius:15px;\n"
"background-color: #9de1f6;\n"
"border: 3px solid black;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.frame_6 = QtWidgets.QFrame(self.frame_3)
        self.frame_6.setGeometry(QtCore.QRect(20, 70, 381, 131))
        self.frame_6.setStyleSheet("background-color:white; border: 3px solid black;")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_5 = QtWidgets.QLabel(self.frame_6)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 361, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(15)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("border:none;")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.lbl_type1 = QtWidgets.QLabel(self.frame_6)
        self.lbl_type1.setGeometry(QtCore.QRect(40, 50, 131, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(12)
        font.setBold(True)
        self.lbl_type1.setFont(font)
        self.lbl_type1.setStyleSheet("background-color: rgb(0, 189, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:30px;")
        self.lbl_type1.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_type1.setObjectName("lbl_type1")
        self.lbl_type2 = QtWidgets.QLabel(self.frame_6)
        self.lbl_type2.setGeometry(QtCore.QRect(200, 50, 131, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(12)
        font.setBold(True)
        self.lbl_type2.setFont(font)
        self.lbl_type2.setStyleSheet("background-color: rgb(136, 68, 204);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:30px;\n"
"")
        self.lbl_type2.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_type2.setObjectName("lbl_type2")
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setGeometry(QtCore.QRect(26, 59, 369, 5))
        self.label_3.setStyleSheet("border:none;\n"
"background-color:white;\n"
"border: 3px solid black;\n"
"\n"
"")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        self.label_4.setGeometry(QtCore.QRect(30, 20, 361, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(20)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("border:none;")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.frame_7 = QtWidgets.QFrame(self.frame_3)
        self.frame_7.setGeometry(QtCore.QRect(20, 220, 381, 151))
        self.frame_7.setStyleSheet("background-color:white; border: 3px solid black;")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.label_7 = QtWidgets.QLabel(self.frame_7)
        self.label_7.setGeometry(QtCore.QRect(10, 10, 361, 21))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("border:none;")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.lbl_abiliti = QtWidgets.QLabel(self.frame_7)
        self.lbl_abiliti.setGeometry(QtCore.QRect(0, 30, 381, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.lbl_abiliti.setFont(font)
        self.lbl_abiliti.setStyleSheet("border-bottom: 1px solid black;\n"
"border-top:none;\n"
"border-radius:none;\n"
"")
        self.lbl_abiliti.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_abiliti.setObjectName("lbl_abiliti")
        self.label_8 = QtWidgets.QLabel(self.frame_7)
        self.label_8.setGeometry(QtCore.QRect(10, 71, 361, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("border:none;\n"
"")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.frame_7)
        self.label_9.setGeometry(QtCore.QRect(6, 110, 371, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(16)
        font.setBold(True)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("border:none;")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.frame_8 = QtWidgets.QFrame(self.frame_3)
        self.frame_8.setGeometry(QtCore.QRect(20, 380, 381, 231))
        self.frame_8.setStyleSheet("background-color:white; border: 3px solid black;")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.Qpb_hp = QtWidgets.QProgressBar(self.frame_8)
        self.Qpb_hp.setGeometry(QtCore.QRect(90, 22, 281, 21))
        self.Qpb_hp.setStyleSheet("QProgressBar{\n"
"background-color: rgb(232, 232, 232);\n"
"border:2px solid black ;\n"
"border-radius:10px;\n"
"}\n"
"\n"
"QProgressBar::chunk{\n"
"background-color: rgb(0, 255, 0);\n"
"border-radius:3px;\n"
"margin: 0.5px;\n"
"\n"
"\n"
"}\n"
"")
        self.Qpb_hp.setProperty("value", 45)
        self.Qpb_hp.setTextVisible(False)
        self.Qpb_hp.setOrientation(QtCore.Qt.Horizontal)
        self.Qpb_hp.setInvertedAppearance(False)
        self.Qpb_hp.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.Qpb_hp.setFormat("")
        self.Qpb_hp.setObjectName("Qpb_hp")
        self.label_10 = QtWidgets.QLabel(self.frame_8)
        self.label_10.setGeometry(QtCore.QRect(10, 24, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(10)
        font.setBold(True)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("border:none")
        self.label_10.setObjectName("label_10")
        self.lbl_hp_value = QtWidgets.QLabel(self.frame_8)
        self.lbl_hp_value.setGeometry(QtCore.QRect(70, 24, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(10)
        font.setBold(True)
        self.lbl_hp_value.setFont(font)
        self.lbl_hp_value.setStyleSheet("border:none")
        self.lbl_hp_value.setObjectName("lbl_hp_value")
        self.Qpb_spdef = QtWidgets.QProgressBar(self.frame_8)
        self.Qpb_spdef.setGeometry(QtCore.QRect(90, 138, 281, 21))
        self.Qpb_spdef.setStyleSheet("QProgressBar{\n"
"background-color: rgb(232, 232, 232);\n"
"border:2px solid black ;\n"
"border-radius:10px;\n"
"}\n"
"\n"
"QProgressBar::chunk{\n"
"background-color: rgb(0, 208, 208);\n"
"border-radius:3px;\n"
"margin: 0.5px;\n"
"\n"
"\n"
"}\n"
"")
        self.Qpb_spdef.setProperty("value", 65)
        self.Qpb_spdef.setTextVisible(False)
        self.Qpb_spdef.setOrientation(QtCore.Qt.Horizontal)
        self.Qpb_spdef.setInvertedAppearance(False)
        self.Qpb_spdef.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.Qpb_spdef.setFormat("")
        self.Qpb_spdef.setObjectName("Qpb_spdef")
        self.lbl_spdef = QtWidgets.QLabel(self.frame_8)
        self.lbl_spdef.setGeometry(QtCore.QRect(70, 140, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(10)
        font.setBold(True)
        self.lbl_spdef.setFont(font)
        self.lbl_spdef.setStyleSheet("border:none;\n"
"background-color: transparent;")
        self.lbl_spdef.setObjectName("lbl_spdef")
        self.label_14 = QtWidgets.QLabel(self.frame_8)
        self.label_14.setGeometry(QtCore.QRect(7, 140, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(9)
        font.setBold(True)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("border:none;\n"
"background-color:transparent;")
        self.label_14.setObjectName("label_14")
        self.lbl_spd = QtWidgets.QLabel(self.frame_8)
        self.lbl_spd.setGeometry(QtCore.QRect(70, 172, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(10)
        font.setBold(True)
        self.lbl_spd.setFont(font)
        self.lbl_spd.setStyleSheet("border:none;\n"
"background-color: transparent;")
        self.lbl_spd.setObjectName("lbl_spd")
        self.label_15 = QtWidgets.QLabel(self.frame_8)
        self.label_15.setGeometry(QtCore.QRect(7, 172, 41, 16))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(10)
        font.setBold(True)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("border:none;\n"
"background-color:transparent;")
        self.label_15.setObjectName("label_15")
        self.Qpb_spd = QtWidgets.QProgressBar(self.frame_8)
        self.Qpb_spd.setGeometry(QtCore.QRect(90, 170, 281, 21))
        self.Qpb_spd.setStyleSheet("QProgressBar{\n"
"background-color: rgb(232, 232, 232);\n"
"border:2px solid black ;\n"
"border-radius:10px;\n"
"}\n"
"\n"
"QProgressBar::chunk{\n"
"background-color: rgb(255, 170, 0);\n"
"border-radius:3px;\n"
"margin: 0.5px;\n"
"\n"
"\n"
"}\n"
"")
        self.Qpb_spd.setProperty("value", 45)
        self.Qpb_spd.setTextVisible(False)
        self.Qpb_spd.setOrientation(QtCore.Qt.Horizontal)
        self.Qpb_spd.setInvertedAppearance(False)
        self.Qpb_spd.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.Qpb_spd.setFormat("")
        self.Qpb_spd.setObjectName("Qpb_spd")
        self.label_16 = QtWidgets.QLabel(self.frame_8)
        self.label_16.setGeometry(QtCore.QRect(10, 200, 41, 16))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("border:none;\n"
"background-color:transparent;")
        self.label_16.setObjectName("label_16")
        self.lbl_total_status = QtWidgets.QLabel(self.frame_8)
        self.lbl_total_status.setGeometry(QtCore.QRect(60, 200, 41, 16))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        self.lbl_total_status.setFont(font)
        self.lbl_total_status.setStyleSheet("border:none;\n"
"background-color:transparent;")
        self.lbl_total_status.setObjectName("lbl_total_status")
        self.Qpb_attack = QtWidgets.QProgressBar(self.centralwidget)
        self.Qpb_attack.setGeometry(QtCore.QRect(660, 448, 281, 21))
        self.Qpb_attack.setStyleSheet("QProgressBar{\n"
"background-color: rgb(232, 232, 232);\n"
"border:2px solid black ;\n"
"border-radius:10px;\n"
"}\n"
"\n"
"QProgressBar::chunk{\n"
"background-color: rgb(255, 0, 0);\n"
"border-radius:3px;\n"
"margin: 0.5px;\n"
"\n"
"\n"
"}\n"
"")
        self.Qpb_attack.setProperty("value", 49)
        self.Qpb_attack.setTextVisible(False)
        self.Qpb_attack.setOrientation(QtCore.Qt.Horizontal)
        self.Qpb_attack.setInvertedAppearance(False)
        self.Qpb_attack.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.Qpb_attack.setFormat("")
        self.Qpb_attack.setObjectName("Qpb_attack")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(577, 450, 41, 16))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(10)
        font.setBold(True)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("border:none;\n"
"background-color:transparent;")
        self.label_11.setObjectName("label_11")
        self.lbl_atk_value = QtWidgets.QLabel(self.centralwidget)
        self.lbl_atk_value.setGeometry(QtCore.QRect(640, 450, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(10)
        font.setBold(True)
        self.lbl_atk_value.setFont(font)
        self.lbl_atk_value.setStyleSheet("border:none;\n"
"background-color: transparent;")
        self.lbl_atk_value.setObjectName("lbl_atk_value")
        self.lbl_defense = QtWidgets.QLabel(self.centralwidget)
        self.lbl_defense.setGeometry(QtCore.QRect(640, 480, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(10)
        font.setBold(True)
        self.lbl_defense.setFont(font)
        self.lbl_defense.setStyleSheet("border:none;\n"
"background-color: transparent;")
        self.lbl_defense.setObjectName("lbl_defense")
        self.Qpb_defense = QtWidgets.QProgressBar(self.centralwidget)
        self.Qpb_defense.setGeometry(QtCore.QRect(660, 478, 281, 21))
        self.Qpb_defense.setStyleSheet("QProgressBar{\n"
"background-color: rgb(232, 232, 232);\n"
"border:2px solid black ;\n"
"border-radius:10px;\n"
"}\n"
"\n"
"QProgressBar::chunk{\n"
"background-color: rgb(255, 255, 0);\n"
"border-radius:3px;\n"
"margin: 0.5px;\n"
"\n"
"\n"
"}\n"
"")
        self.Qpb_defense.setProperty("value", 49)
        self.Qpb_defense.setTextVisible(False)
        self.Qpb_defense.setOrientation(QtCore.Qt.Horizontal)
        self.Qpb_defense.setInvertedAppearance(False)
        self.Qpb_defense.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.Qpb_defense.setFormat("")
        self.Qpb_defense.setObjectName("Qpb_defense")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(577, 480, 51, 16))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(10)
        font.setBold(True)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("border:none;\n"
"background-color:transparent;")
        self.label_12.setObjectName("label_12")
        self.lbl_spatk = QtWidgets.QLabel(self.centralwidget)
        self.lbl_spatk.setGeometry(QtCore.QRect(640, 512, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(10)
        font.setBold(True)
        self.lbl_spatk.setFont(font)
        self.lbl_spatk.setStyleSheet("border:none;\n"
"background-color: transparent;")
        self.lbl_spatk.setObjectName("lbl_spatk")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(577, 512, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(10)
        font.setBold(True)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("border:none;\n"
"background-color:transparent;")
        self.label_13.setObjectName("label_13")
        self.Qpb_spatk = QtWidgets.QProgressBar(self.centralwidget)
        self.Qpb_spatk.setGeometry(QtCore.QRect(660, 510, 281, 21))
        self.Qpb_spatk.setStyleSheet("QProgressBar{\n"
"background-color: rgb(232, 232, 232);\n"
"border:2px solid black ;\n"
"border-radius:10px;\n"
"}\n"
"\n"
"QProgressBar::chunk{\n"
"background-color: rgb(6, 126, 255);\n"
"border-radius:3px;\n"
"margin: 0.5px;\n"
"\n"
"\n"
"}\n"
"")
        self.Qpb_spatk.setProperty("value", 65)
        self.Qpb_spatk.setTextVisible(False)
        self.Qpb_spatk.setOrientation(QtCore.Qt.Horizontal)
        self.Qpb_spatk.setInvertedAppearance(False)
        self.Qpb_spatk.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.Qpb_spatk.setFormat("")
        self.Qpb_spatk.setObjectName("Qpb_spatk")
        self.btn_last = QtWidgets.QPushButton(self.centralwidget)
        self.btn_last.setGeometry(QtCore.QRect(580, 660, 141, 71))
        self.btn_last.setMinimumSize(QtCore.QSize(141, 71))
        self.btn_last.setMaximumSize(QtCore.QSize(141, 71))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(10)
        font.setBold(True)
        self.btn_last.setFont(font)
        self.btn_last.setStyleSheet("QPushButton{\n"
"background-image: url(C:/Users/Yuri/PycharmProject/Pokedex/img/left1.png);\n"
"background-repeat:no-repeat;\n"
"background-size:auto;\n"
"border:none;\n"
"color:white;\n"
"text-align:right;\n"
"padding-right:15px;\n"
"}\n"
"\n"
"QPushButton:Hover{\n"
"background-image: url(C:/Users/Yuri/PycharmProject/Pokedex/img/left2.png);\n"
"background-repeat:no-repeat;\n"
"background-size:auto;\n"
"border:none;\n"
"}")
        self.btn_last.setDefault(False)
        self.btn_last.setObjectName("btn_last")
        self.btn_next = QtWidgets.QPushButton(self.centralwidget)
        self.btn_next.setGeometry(QtCore.QRect(740, 660, 141, 71))
        self.btn_next.setMinimumSize(QtCore.QSize(141, 71))
        self.btn_next.setMaximumSize(QtCore.QSize(141, 71))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(10)
        font.setBold(True)
        self.btn_next.setFont(font)
        self.btn_next.setStyleSheet("QPushButton{\n"
"background-image: url(C:/Users/Yuri/PycharmProject/Pokedex/img/right1.png);\n"
"background-repeat:no-repeat;\n"
"background-size:auto;\n"
"border:none;\n"
"color:white;\n"
"text-align:left;\n"
"padding-left:38px;\n"
"}\n"
"\n"
"QPushButton:Hover{\n"
"background-image: url(C:/Users/Yuri/PycharmProject/Pokedex/img/right2.png);\n"
"background-repeat:no-repeat;\n"
"background-size:auto;\n"
"border:none;\n"
"text-align:left;\n"
"padding-left:28px;\n"
"\n"
"\n"
"}")
        self.btn_next.setObjectName("btn_next")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Pokédex"))
        self.label.setText(_translate("MainWindow", "Ivysaur"))
        self.lbl_id.setText(_translate("MainWindow", "#002"))
        self.txtedt_desc.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Yu Gothic UI Semibold\'; font-size:10pt; font-weight:700; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">A legendary bird POKÉMON that is said to appear from clouds while dropping enormous lightning bolts.</p></body></html>"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Search by name"))
        self.btn_search.setText(_translate("MainWindow", "Search"))
        self.label_5.setText(_translate("MainWindow", "Type"))
        self.lbl_type1.setText(_translate("MainWindow", "Grass"))
        self.lbl_type2.setText(_translate("MainWindow", "Poison"))
        self.label_4.setText(_translate("MainWindow", "Informations"))
        self.label_7.setText(_translate("MainWindow", "Abilities"))
        self.lbl_abiliti.setText(_translate("MainWindow", "overgrow"))
        self.label_8.setText(_translate("MainWindow", "Hidden ability"))
        self.label_9.setText(_translate("MainWindow", "chlorophyll"))
        self.label_10.setText(_translate("MainWindow", "HP"))
        self.lbl_hp_value.setText(_translate("MainWindow", "45"))
        self.lbl_spdef.setText(_translate("MainWindow", "65"))
        self.label_14.setText(_translate("MainWindow", "Sp.Defense"))
        self.lbl_spd.setText(_translate("MainWindow", "45"))
        self.label_15.setText(_translate("MainWindow", "Speed"))
        self.label_16.setText(_translate("MainWindow", "Total"))
        self.lbl_total_status.setText(_translate("MainWindow", "318"))
        self.label_11.setText(_translate("MainWindow", "Attack"))
        self.lbl_atk_value.setText(_translate("MainWindow", "49"))
        self.lbl_defense.setText(_translate("MainWindow", "49"))
        self.label_12.setText(_translate("MainWindow", "Defense"))
        self.lbl_spatk.setText(_translate("MainWindow", "65"))
        self.label_13.setText(_translate("MainWindow", "Sp.Attack"))
        self.btn_last.setText(_translate("MainWindow", "Previous"))
        self.btn_next.setText(_translate("MainWindow", "Next"))
